os: linux
services: docker
language: minimal
install: skip
addons:
  apt:
    packages:
    - docker-ce
    - pass
script: "./build/build_img_dev.sh"
deploy:
  provider: script
  skip_cleanup: true
  script: ./build/docker_login.sh && docker push filebrowser/dev && docker logout
  on:
    repo: filebrowser/filebrowser
    branch: chore/devenv